CREATE DATABASE STREAMING222;
GO
USE STREAMING222;
GO

CREATE TABLE PRODUTO(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(250) NULL,
	TIPO CHAR(1) NULL,
	VALOR DECIMAL(5,2) NOT NULL
);
ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY(ID);
GO